print('========================================================================')
print('Sollicitatie formulier.')
print('Hier wat vragen over het sollicatie over een ruimtevuilisman.')
print('Deze vragen zijn erg streng dus wees bewust van je antwoorden!')
print('Wees relaxed en hier komen de vragen!')
print('========================================================================')

Naam = str(input('Wat is uw naam? '))
Hoelang = int(input('Hoe lang bent u? ')) 
Kilo = int(input('Hoeveel kilo bent u? '))
Certifaat = input('Heeft u een "Certificaat Overleven met gevaarlijk personeel"? J/N ')
Man = input('Bent u een man of een vrouw? ')
snorofhaar = input('Is uw snor breder dan 10 cm of als vrouw een rode krulhaar die langer is dan 20cm? J/N ')
Hoed = input('Heeft u een hoge hoed? J/N ')
Vracht = input('Heeft u een geldige Vrachtwagen rijbewijs? J/N ')
mbo = input('Heeft u een MBO-4 diploma ondernemen? J/N ')
Praktijk = int(input('Hoeveel jaar praktijkervaring met dieren-dressuur heeft u? '))
jongleren = int(input ('Hoeveel jaar ervaring heeft u met jongleren? '))
Acrobatiek = int(input('Hoeveel jaar praktijkervaring heeft u met Acrobatiek? '))
if  Hoelang <150 or Kilo <90 or Certifaat == 'n' or snorofhaar == 'n' or Hoed == 'n' or Vracht == 'n' or mbo == 'n' or Praktijk <4 or jongleren <5 or Acrobatiek <3:
    str(print('Beste')) + str(print(Naam)) + str(print('Helaas, u voldoet u niet aan onze strenge eisen, het spijt ons!'))
else: str(print('Beste')) + str(print(Naam)) + str(print('Gefeliciteerd! U komt in aanmerking met een sollicitatiegesprek'))